<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.12" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.12" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.12" />
		<PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
		<PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.0.1" />
	</ItemGroup>

</Project>
